// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: game.proto

package gamepb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GameErrorCode int32

const (
	GameErrorCode_NoError          GameErrorCode = 0
	GameErrorCode_GameSessionError GameErrorCode = 1
	GameErrorCode_NotCreateUser    GameErrorCode = 2 //未创建用户
	GameErrorCode_NickAlreadyExist GameErrorCode = 3 //用户名已存在
	GameErrorCode_NickIsTooShort   GameErrorCode = 4 //用户名太短
	GameErrorCode_NickIsTooLong    GameErrorCode = 5 //用户名太长 昵称长度3-12个字符
	GameErrorCode_UserIsCreated    GameErrorCode = 6 //已经创建用户
)

// Enum value maps for GameErrorCode.
var (
	GameErrorCode_name = map[int32]string{
		0: "NoError",
		1: "GameSessionError",
		2: "NotCreateUser",
		3: "NickAlreadyExist",
		4: "NickIsTooShort",
		5: "NickIsTooLong",
		6: "UserIsCreated",
	}
	GameErrorCode_value = map[string]int32{
		"NoError":          0,
		"GameSessionError": 1,
		"NotCreateUser":    2,
		"NickAlreadyExist": 3,
		"NickIsTooShort":   4,
		"NickIsTooLong":    5,
		"UserIsCreated":    6,
	}
)

func (x GameErrorCode) Enum() *GameErrorCode {
	p := new(GameErrorCode)
	*p = x
	return p
}

func (x GameErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (GameErrorCode) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x GameErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameErrorCode.Descriptor instead.
func (GameErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type GamePbType_TypeEnum int32

const (
	GamePbType_NotUse           GamePbType_TypeEnum = 0 //don't modify this
	GamePbType_EnterGameReq     GamePbType_TypeEnum = 30001
	GamePbType_EnterGameAck     GamePbType_TypeEnum = 30002
	GamePbType_CreateUserReq    GamePbType_TypeEnum = 30003
	GamePbType_CreateUserAck    GamePbType_TypeEnum = 30004
	GamePbType_PackageReq       GamePbType_TypeEnum = 30005
	GamePbType_PackageAck       GamePbType_TypeEnum = 30006
	GamePbType_EquipmentReq     GamePbType_TypeEnum = 30007
	GamePbType_EquipmentAck     GamePbType_TypeEnum = 30008
	GamePbType_AdminCmdReq      GamePbType_TypeEnum = 30009
	GamePbType_AdminCmdAck      GamePbType_TypeEnum = 30010
	GamePbType_PlayerMove       GamePbType_TypeEnum = 30011
	GamePbType_OtherPlayerMove  GamePbType_TypeEnum = 30012
	GamePbType_EnterScene       GamePbType_TypeEnum = 30013
	GamePbType_PlayerEnterScene GamePbType_TypeEnum = 30014
	GamePbType_PlayerExitScene  GamePbType_TypeEnum = 30015
)

// Enum value maps for GamePbType_TypeEnum.
var (
	GamePbType_TypeEnum_name = map[int32]string{
		0:     "NotUse",
		30001: "EnterGameReq",
		30002: "EnterGameAck",
		30003: "CreateUserReq",
		30004: "CreateUserAck",
		30005: "PackageReq",
		30006: "PackageAck",
		30007: "EquipmentReq",
		30008: "EquipmentAck",
		30009: "AdminCmdReq",
		30010: "AdminCmdAck",
		30011: "PlayerMove",
		30012: "OtherPlayerMove",
		30013: "EnterScene",
		30014: "PlayerEnterScene",
		30015: "PlayerExitScene",
	}
	GamePbType_TypeEnum_value = map[string]int32{
		"NotUse":           0,
		"EnterGameReq":     30001,
		"EnterGameAck":     30002,
		"CreateUserReq":    30003,
		"CreateUserAck":    30004,
		"PackageReq":       30005,
		"PackageAck":       30006,
		"EquipmentReq":     30007,
		"EquipmentAck":     30008,
		"AdminCmdReq":      30009,
		"AdminCmdAck":      30010,
		"PlayerMove":       30011,
		"OtherPlayerMove":  30012,
		"EnterScene":       30013,
		"PlayerEnterScene": 30014,
		"PlayerExitScene":  30015,
	}
)

func (x GamePbType_TypeEnum) Enum() *GamePbType_TypeEnum {
	p := new(GamePbType_TypeEnum)
	*p = x
	return p
}

func (x GamePbType_TypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamePbType_TypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (GamePbType_TypeEnum) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x GamePbType_TypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamePbType_TypeEnum.Descriptor instead.
func (GamePbType_TypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16, 0}
}

type EnterGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32  `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	UserID  int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Session string `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *EnterGameReq) Reset() {
	*x = EnterGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameReq) ProtoMessage() {}

func (x *EnterGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameReq.ProtoReflect.Descriptor instead.
func (*EnterGameReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *EnterGameReq) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *EnterGameReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *EnterGameReq) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type EnterGameAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32         `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error   int32         `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message string        `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Err     GameErrorCode `protobuf:"varint,1,opt,name=err,proto3,enum=gamepb.GameErrorCode" json:"err,omitempty"`
	Info    *UserInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *EnterGameAck) Reset() {
	*x = EnterGameAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameAck) ProtoMessage() {}

func (x *EnterGameAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameAck.ProtoReflect.Descriptor instead.
func (*EnterGameAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *EnterGameAck) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *EnterGameAck) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *EnterGameAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnterGameAck) GetErr() GameErrorCode {
	if x != nil {
		return x.Err
	}
	return GameErrorCode_NoError
}

func (x *EnterGameAck) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId  int32  `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Nick   string `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Gender int32  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"` //1=男，2=女
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReq) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *CreateUserReq) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *CreateUserReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type CreateUserAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32         `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error   int32         `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message string        `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Err     GameErrorCode `protobuf:"varint,1,opt,name=err,proto3,enum=gamepb.GameErrorCode" json:"err,omitempty"`
	Info    *UserInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *CreateUserAck) Reset() {
	*x = CreateUserAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAck) ProtoMessage() {}

func (x *CreateUserAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAck.ProtoReflect.Descriptor instead.
func (*CreateUserAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserAck) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *CreateUserAck) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *CreateUserAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateUserAck) GetErr() GameErrorCode {
	if x != nil {
		return x.Err
	}
	return GameErrorCode_NoError
}

func (x *CreateUserAck) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PackageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
}

func (x *PackageReq) Reset() {
	*x = PackageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageReq) ProtoMessage() {}

func (x *PackageReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageReq.ProtoReflect.Descriptor instead.
func (*PackageReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *PackageReq) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type PackageAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32          `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error   int32          `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message string         `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Infos   []*PackageInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *PackageAck) Reset() {
	*x = PackageAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageAck) ProtoMessage() {}

func (x *PackageAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageAck.ProtoReflect.Descriptor instead.
func (*PackageAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *PackageAck) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *PackageAck) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *PackageAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PackageAck) GetInfos() []*PackageInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type EquipmentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId int32 `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
}

func (x *EquipmentReq) Reset() {
	*x = EquipmentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentReq) ProtoMessage() {}

func (x *EquipmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentReq.ProtoReflect.Descriptor instead.
func (*EquipmentReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *EquipmentReq) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type EquipmentAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32            `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error   int32            `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message string           `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Equips  []*EquipmentInfo `protobuf:"bytes,1,rep,name=equips,proto3" json:"equips,omitempty"`
}

func (x *EquipmentAck) Reset() {
	*x = EquipmentAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentAck) ProtoMessage() {}

func (x *EquipmentAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentAck.ProtoReflect.Descriptor instead.
func (*EquipmentAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *EquipmentAck) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *EquipmentAck) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *EquipmentAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EquipmentAck) GetEquips() []*EquipmentInfo {
	if x != nil {
		return x.Equips
	}
	return nil
}

type AdminCmdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//AddPackage itemId num     --add package
	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	//zero is to me,other is to other user
	UserID int64 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	RpcId  int32 `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
}

func (x *AdminCmdReq) Reset() {
	*x = AdminCmdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCmdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCmdReq) ProtoMessage() {}

func (x *AdminCmdReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCmdReq.ProtoReflect.Descriptor instead.
func (*AdminCmdReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *AdminCmdReq) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *AdminCmdReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AdminCmdReq) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type AdminCmdAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32  `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error   int32  `protobuf:"varint,91,opt,name=Error,proto3" json:"Error,omitempty"`
	Message string `protobuf:"bytes,92,opt,name=Message,proto3" json:"Message,omitempty"`
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrStr  string `protobuf:"bytes,2,opt,name=errStr,proto3" json:"errStr,omitempty"`
}

func (x *AdminCmdAck) Reset() {
	*x = AdminCmdAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCmdAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCmdAck) ProtoMessage() {}

func (x *AdminCmdAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCmdAck.ProtoReflect.Descriptor instead.
func (*AdminCmdAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *AdminCmdAck) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *AdminCmdAck) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *AdminCmdAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminCmdAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminCmdAck) GetErrStr() string {
	if x != nil {
		return x.ErrStr
	}
	return ""
}

type PlayerMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X     int32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     int32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Speed float32 `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerMove) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMove) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerMove) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type OtherPlayerMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    int64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	X         int32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y         int32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Speed     float32 `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Timestamp int64   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *OtherPlayerMove) Reset() {
	*x = OtherPlayerMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtherPlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherPlayerMove) ProtoMessage() {}

func (x *OtherPlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherPlayerMove.ProtoReflect.Descriptor instead.
func (*OtherPlayerMove) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *OtherPlayerMove) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OtherPlayerMove) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *OtherPlayerMove) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *OtherPlayerMove) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *OtherPlayerMove) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type JumpScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToSceneID int32 `protobuf:"varint,1,opt,name=toSceneID,proto3" json:"toSceneID,omitempty"`
	X         int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y         int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *JumpScene) Reset() {
	*x = JumpScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JumpScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpScene) ProtoMessage() {}

func (x *JumpScene) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpScene.ProtoReflect.Descriptor instead.
func (*JumpScene) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *JumpScene) GetToSceneID() int32 {
	if x != nil {
		return x.ToSceneID
	}
	return 0
}

func (x *JumpScene) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *JumpScene) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type EnterScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneID int32 `protobuf:"varint,1,opt,name=sceneID,proto3" json:"sceneID,omitempty"`
	X       int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *EnterScene) Reset() {
	*x = EnterScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterScene) ProtoMessage() {}

func (x *EnterScene) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterScene.ProtoReflect.Descriptor instead.
func (*EnterScene) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *EnterScene) GetSceneID() int32 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

func (x *EnterScene) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EnterScene) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerExitScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *PlayerExitScene) Reset() {
	*x = PlayerExitScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerExitScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerExitScene) ProtoMessage() {}

func (x *PlayerExitScene) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerExitScene.ProtoReflect.Descriptor instead.
func (*PlayerExitScene) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerExitScene) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type PlayerEnterScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SceneID   int32 `protobuf:"varint,2,opt,name=sceneID,proto3" json:"sceneID,omitempty"`
	X         int32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y         int32 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PlayerEnterScene) Reset() {
	*x = PlayerEnterScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerEnterScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterScene) ProtoMessage() {}

func (x *PlayerEnterScene) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterScene.ProtoReflect.Descriptor instead.
func (*PlayerEnterScene) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerEnterScene) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PlayerEnterScene) GetSceneID() int32 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

func (x *PlayerEnterScene) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerEnterScene) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerEnterScene) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GamePbType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GamePbType) Reset() {
	*x = GamePbType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePbType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePbType) ProtoMessage() {}

func (x *GamePbType) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePbType.ProtoReflect.Descriptor instead.
func (*GamePbType) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16}
}

type EquipmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32  `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassID int32  `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`
	Pos     uint32 `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *EquipmentInfo) Reset() {
	*x = EquipmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentInfo) ProtoMessage() {}

func (x *EquipmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentInfo.ProtoReflect.Descriptor instead.
func (*EquipmentInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{17}
}

func (x *EquipmentInfo) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *EquipmentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentInfo) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *EquipmentInfo) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

type PackageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32  `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassID int32  `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`
	Pos     uint32 `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Num     int32  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{18}
}

func (x *PackageInfo) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *PackageInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PackageInfo) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *PackageInfo) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *PackageInfo) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcId   int32  `protobuf:"varint,90,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Nick    string `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Exp     int32  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Level   int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Score   int64  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"` //游戏币
	Gold    int32  `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`   //充值币
	Gender  int32  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	SceneID int32  `protobuf:"varint,7,opt,name=sceneID,proto3" json:"sceneID,omitempty"` //玩家所在场景id
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{19}
}

func (x *UserInfo) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *UserInfo) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserInfo) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserInfo) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetSceneID() int32 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x70, 0x62, 0x22, 0x56, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xa3, 0x01, 0x0a,
	0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70,
	0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x5b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x5c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x24, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x51, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0xa4, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64,
	0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x5b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x5c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x24, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x22, 0x0a, 0x0a,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70,
	0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64,
	0x22, 0x7d, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52,
	0x70, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x5b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x5c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22,
	0x24, 0x0a, 0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x52, 0x70, 0x63, 0x49, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18,
	0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x5b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x5c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x06,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x65, 0x71, 0x75, 0x69, 0x70, 0x73, 0x22, 0x4d, 0x0a, 0x0b, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70,
	0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x5b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x5c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x53,
	0x74, 0x72, 0x22, 0x3e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x22, 0x79, 0x0a, 0x0f, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x45, 0x0a,
	0x09, 0x4a, 0x75, 0x6d, 0x70, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x6f, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x79, 0x22, 0x42, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x29, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x7e, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0xd3, 0x02, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x62, 0x54, 0x79,
	0x70, 0x65, 0x22, 0xc4, 0x02, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12,
	0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x55, 0x73, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0c, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x10, 0xb1, 0xea, 0x01, 0x12,
	0x12, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x6b, 0x10,
	0xb2, 0xea, 0x01, 0x12, 0x13, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x10, 0xb3, 0xea, 0x01, 0x12, 0x13, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x10, 0xb4, 0xea, 0x01, 0x12, 0x10, 0x0a,
	0x0a, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x10, 0xb5, 0xea, 0x01, 0x12,
	0x10, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x10, 0xb6, 0xea,
	0x01, 0x12, 0x12, 0x0a, 0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x10, 0xb7, 0xea, 0x01, 0x12, 0x12, 0x0a, 0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x63, 0x6b, 0x10, 0xb8, 0xea, 0x01, 0x12, 0x11, 0x0a, 0x0b, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x10, 0xb9, 0xea, 0x01, 0x12, 0x11, 0x0a, 0x0b,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x41, 0x63, 0x6b, 0x10, 0xba, 0xea, 0x01, 0x12,
	0x10, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x10, 0xbb, 0xea,
	0x01, 0x12, 0x15, 0x0a, 0x0f, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4d, 0x6f, 0x76, 0x65, 0x10, 0xbc, 0xea, 0x01, 0x12, 0x10, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0xbd, 0xea, 0x01, 0x12, 0x16, 0x0a, 0x10, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0xbe,
	0xea, 0x01, 0x12, 0x15, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x10, 0xbf, 0xea, 0x01, 0x22, 0x61, 0x0a, 0x0d, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x70,
	0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x71, 0x0a, 0x0b,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x52,
	0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22,
	0xb8, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x52, 0x70, 0x63, 0x49, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x70, 0x63,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x44, 0x2a, 0x95, 0x01, 0x0a, 0x0d, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x4e, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x69, 0x63, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x69, 0x63, 0x6b,
	0x49, 0x73, 0x54, 0x6f, 0x6f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d,
	0x4e, 0x69, 0x63, 0x6b, 0x49, 0x73, 0x54, 0x6f, 0x6f, 0x4c, 0x6f, 0x6e, 0x67, 0x10, 0x05, 0x12,
	0x11, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x10, 0x06, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_game_proto_goTypes = []interface{}{
	(GameErrorCode)(0),       // 0: gamepb.GameErrorCode
	(GamePbType_TypeEnum)(0), // 1: gamepb.GamePbType.TypeEnum
	(*EnterGameReq)(nil),     // 2: gamepb.EnterGameReq
	(*EnterGameAck)(nil),     // 3: gamepb.EnterGameAck
	(*CreateUserReq)(nil),    // 4: gamepb.CreateUserReq
	(*CreateUserAck)(nil),    // 5: gamepb.CreateUserAck
	(*PackageReq)(nil),       // 6: gamepb.PackageReq
	(*PackageAck)(nil),       // 7: gamepb.PackageAck
	(*EquipmentReq)(nil),     // 8: gamepb.EquipmentReq
	(*EquipmentAck)(nil),     // 9: gamepb.EquipmentAck
	(*AdminCmdReq)(nil),      // 10: gamepb.AdminCmdReq
	(*AdminCmdAck)(nil),      // 11: gamepb.AdminCmdAck
	(*PlayerMove)(nil),       // 12: gamepb.PlayerMove
	(*OtherPlayerMove)(nil),  // 13: gamepb.OtherPlayerMove
	(*JumpScene)(nil),        // 14: gamepb.JumpScene
	(*EnterScene)(nil),       // 15: gamepb.EnterScene
	(*PlayerExitScene)(nil),  // 16: gamepb.PlayerExitScene
	(*PlayerEnterScene)(nil), // 17: gamepb.PlayerEnterScene
	(*GamePbType)(nil),       // 18: gamepb.GamePbType
	(*EquipmentInfo)(nil),    // 19: gamepb.EquipmentInfo
	(*PackageInfo)(nil),      // 20: gamepb.PackageInfo
	(*UserInfo)(nil),         // 21: gamepb.UserInfo
}
var file_game_proto_depIdxs = []int32{
	0,  // 0: gamepb.EnterGameAck.err:type_name -> gamepb.GameErrorCode
	21, // 1: gamepb.EnterGameAck.info:type_name -> gamepb.UserInfo
	0,  // 2: gamepb.CreateUserAck.err:type_name -> gamepb.GameErrorCode
	21, // 3: gamepb.CreateUserAck.info:type_name -> gamepb.UserInfo
	20, // 4: gamepb.PackageAck.infos:type_name -> gamepb.PackageInfo
	19, // 5: gamepb.EquipmentAck.equips:type_name -> gamepb.EquipmentInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCmdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCmdAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtherPlayerMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JumpScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerExitScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerEnterScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePbType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
