// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "error.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ErrCode {

namespace {

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_error_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_error_2eproto() {
  protobuf_AddDesc_error_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "error.proto");
  GOOGLE_CHECK(file != NULL);
  ErrorCode_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_error_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_error_2eproto() {
}

void protobuf_InitDefaults_error_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_error_2eproto_once_);
void protobuf_InitDefaults_error_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_error_2eproto_once_,
                 &protobuf_InitDefaults_error_2eproto_impl);
}
void protobuf_AddDesc_error_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_error_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013error.proto\022\007ErrCode*\251\005\n\tErrorCode\022\013\n\007"
    "NoError\020\000\022\021\n\rErrorPassword\020\001\022\020\n\014HaveUser"
    "Name\020\002\022\017\n\013IllegalName\020\003\022\020\n\014ErrorSession\020"
    "\004\022\016\n\nNoUserInfo\020\005\022\023\n\017ToUserIsOffline\020\006\022\022"
    "\n\016DoTaskHeroInCD\020\007\022\016\n\nNoThisHero\020\010\022\024\n\020Ta"
    "rgetUnfinished\020\t\022\024\n\020TooManyRecvQuest\020\n\022\013"
    "\n\007NoMoney\020\013\022\016\n\nNoThisItem\020\014\022\021\n\rItemNotEn"
    "ough\020\r\022\016\n\nNoMaterial\020\016\022\031\n\025NotEnoughContr"
    "ibution\020\017\022\017\n\013EvolveError\020\020\022\022\n\016NotEnoughP"
    "ower\020\021\022\024\n\020RefresshCycError\020\022\022\026\n\022SelectCy"
    "cDiffError\020\023\022\024\n\020AlreadyRecruited\020\024\022\013\n\007No"
    "Times\020\025\022\031\n\025AdvantureEventNotDone\020\026\022\020\n\014No"
    "Provisions\020\027\022\030\n\024FriendShipLevelError\020\030\022\021"
    "\n\rMoreEmptyBook\020\031\022\024\n\020EmptyBookIsError\020\032\022"
    "\021\n\rItemTypeError\020\033\022\016\n\nNoThisCity\020\034\022\017\n\013No"
    "ThisField\020\035\022\031\n\025WorldWarSceneNotStart\020\036\022\026"
    "\n\022CreateClusterError\020\037\022\024\n\020JoinClusterErr"
    "or\020 \022\024\n\020ExitClusterError\020!b\006proto3", 714);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "error.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_error_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_error_2eproto_once_);
void protobuf_AddDesc_error_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_error_2eproto_once_,
                 &protobuf_AddDesc_error_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_error_2eproto {
  StaticDescriptorInitializer_error_2eproto() {
    protobuf_AddDesc_error_2eproto();
  }
} static_descriptor_initializer_error_2eproto_;
const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ErrorCode_descriptor_;
}
bool ErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ErrCode

// @@protoc_insertion_point(global_scope)
